CREATE TABLE DOCTOR(
  DOCTOR_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  DOCTOR_NUMBER CHAR(2) NOT NULL UNIQUE,
  DOCTOR_INFO CHAR(2) NOT NULL
);

CREATE TABLE PATIENT(
  PATIENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  CITY VARCHAR(24),
  PHONE_NUMBER VARCHAR(24)
);

CREATE TABLE APPOINTMENT(
  APPOINTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  DOCTOR_ID BIGINT NOT NULL,
  PATIENT_ID BIGINT NOT NULL,
  APP_DATE DATE
);

ALTER TABLE APPOINTMENT ADD FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID);
ALTER TABLE APPOINTMENT ADD FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID);
CREATE INDEX IDX_APP_DATE_ ON APPOINTMENT(APP_DATE);
